#!/bin/bash

katse=$(dpkg-query -W -f='${Status}' phpmyadmin | grep -c 'ok installed')

if [ $katse = "1" ]; then

        echo " PHPMyAdmin server on juba paigaldatud "
       # service mysql status

else
        echo   "Kas soovite paigaldada PHPMyAdmini Y/N"
read vastus

        if [ $vastus = Y ]; then
        apt-get install phpmyadmin --assume-yes

elif
        [ $vastus = y ]; then
        apt-get install phpmyadmin --assume-yes


elif
        [ $vastus = N ]; then
        exit

fi
fi


