#!/bin/bash

kasutajanimi=$1

#Viime sisse muudatused apache configis
sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf

#Aktiveerime vajaliku mooduli ja teeme apachele restardi
a2enmod userdir

systemctl restart apache2

#Loome kasutaja ning tema kodukataloogi ning seal sees kausta public
useradd -m -s /bin/bash $kasutajanimi 

mkdir /home/$kasutajanimi/public

