#!/bin/bash

kasutajanimi=$1

sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf

a2enmod userdir

systemctl restart apache2

useradd -m -s /bin/bash $kasutajanimi 

mkdir /home/$kasutajanimi/public

